In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
one_hot_repr = [one_hot(word,voc_size) for word in sent]
one_hot_repr

[[708, 7954, 1998, 6438],
 [708, 7954, 1998, 7568],
 [708, 9174, 1998, 6621],
 [6033, 8886, 6794, 2073, 1612],
 [6033, 8886, 6794, 2073, 3302],
 [8928, 708, 7863, 1998, 8233],
 [7001, 7161, 5450, 2073]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length=8 #Considering maximum words in sent is 5
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  708 7954 1998 6438]
 [   0    0    0    0  708 7954 1998 7568]
 [   0    0    0    0  708 9174 1998 6621]
 [   0    0    0 6033 8886 6794 2073 1612]
 [   0    0    0 6033 8886 6794 2073 3302]
 [   0    0    0 8928  708 7863 1998 8233]
 [   0    0    0    0 7001 7161 5450 2073]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 114ms/step


array([[[-0.03679786, -0.03441509,  0.04454676,  0.0081883 ,
         -0.02840656, -0.02464781,  0.0371199 , -0.00940541,
         -0.00939535,  0.02940292],
        [-0.03679786, -0.03441509,  0.04454676,  0.0081883 ,
         -0.02840656, -0.02464781,  0.0371199 , -0.00940541,
         -0.00939535,  0.02940292],
        [-0.03679786, -0.03441509,  0.04454676,  0.0081883 ,
         -0.02840656, -0.02464781,  0.0371199 , -0.00940541,
         -0.00939535,  0.02940292],
        [-0.03679786, -0.03441509,  0.04454676,  0.0081883 ,
         -0.02840656, -0.02464781,  0.0371199 , -0.00940541,
         -0.00939535,  0.02940292],
        [-0.04472666, -0.03927695,  0.02172578, -0.01489508,
         -0.0376768 , -0.00924677, -0.02495726,  0.03806827,
          0.02226403,  0.04771182],
        [ 0.01979433, -0.01754867, -0.02674804, -0.02473044,
          0.00451975, -0.00786011, -0.03640961, -0.02886707,
         -0.04067602, -0.00469466],
        [-0.00282983, -0.04166009,  0.02121905, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531